# Álgebra Lineal con Python

Recordemos que si damos $n\times m$ números reales, entonces podemos crear un arreglo (una matriz):
$$A_{m\times n}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

y al conjunto de matrices con coeficientes en $\mathbb{R}$ lo denotamos $\text{Mat}_{m\times n}(\mathbb{R})$.


In [2]:
type(2), type(2.0), type("2") # La función type(obj) nos dice el tipo de objeto con el que se está trabajando.

(int, float, str)

### Variables
$$\text{nombre} = \text{objeto}$$

Debug: $\text{print(variable)}$

1. Suma de matrices

$$\begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} + \begin{pmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{pmatrix} = \begin{pmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{pmatrix}$$

2. Multiplicación de matrices

$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \times \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{pmatrix} $$

In [3]:
variable = "Hola"

x = 5

Cesar = {1, 2, "perro"}

print(variable)

print(x)


Hola
5


In [4]:
variable + str(x)

'Hola5'

### Listas

$L=[a_{0}, a_{1}, \dots, a_{n-1}]$

In [5]:
L = [1, 2, 3, 4, 5]

M = [6, 7, 8, 9 , 10]

N = [11, 12, 13]

print(L)
print(M)  # me muestra el resultado
print(N)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13]


In [6]:
type(L)

list

In [7]:
L_set = set(L)

L_set

{1, 2, 3, 4, 5}

In [8]:
L_lista = list(L_set)
L_lista

[1, 2, 3, 4, 5]

In [9]:
L + M # concatena (no realiza operaciones vectoriales).

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
L + M + N

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

### NumPy

- Un vector = arreglo 1D en Python
- Una matriz = arreglo 2D en Python

In [11]:
import numpy as np

In [12]:
L_vector = np.array(L) # Convertir una lista en un vector

L_vector

array([1, 2, 3, 4, 5])

In [13]:
type(L_vector)

numpy.ndarray

In [14]:
M_vector = np.array(M)

N_vector = np.array(N)

print(M_vector)
print(N_vector)

[ 6  7  8  9 10]
[11 12 13]


In [15]:
len(L_vector), len(M_vector), len(N_vector)

(5, 5, 3)

In [16]:
L_vector + M_vector # suma vectorial

array([ 7,  9, 11, 13, 15])

## Creando matrices con NumPy: El método `solve( , )`


En una tienda de deportes, se venden camisetas y shorts. Un cliente compra 3 camisetas y 2 shorts por un total de $70.

Otro cliente compra 2 camisetas y 4 shorts por un total de $80.

¿Cuál es el precio de una camiseta y el precio de un short? Llamemos \( x \) al precio de una camiseta y \( y \) al precio de un short.

Podemos formular las siguientes ecuaciones basadas en la información dada:

 \begin{cases} 3x + 2y = 70 \\ 2x + 4y = 80 \end{cases}

In [18]:
# Escribimos la mariz asociada al sistema de ecuaciones.
A = np.array([3, 2, 2, 4]).reshape((2,2)) #"Reshape" va a convertir la matriz en 2x2
A

array([[3, 2],
       [2, 4]])

In [19]:
B = np.array([70,80])

$$AX=B$$

##NumPy tiene una sublibrería que se llama Linalg, en donde se pueden resolver sistemas de ecuaciones.

In [20]:
#"solve" resuelve el sistema de ecuaciones
X = np.linalg.solve(A,B)

X

array([15. , 12.5])

La solución al sistema de ecuaciones es
x=15  
y=12.5
